name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run lint
        run: npm run lint
      - name: Run format
        run: npm run format
      - name: Run docs
        run: npm run docs
      - name: Run against junit
        run: npm run e2e:junit
      - name: Run against minitest
        run: npm run e2e:minitest
      - name: Run against surefire
        run: npm run run:surefire
      - name: Run against glob
        run: npm run run:glob
